services:
  ponkodock:
    build:
      context: .
      dockerfile: PonkoDockApp/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: []
